fix: adding full Podman Desktop logo
lima-vm/lima pull request #1835
Opened 2023-09-24 17:05 UTC by mairin

Logo previously only included the logomark and not the logotype. This version includes the logotype so the name of the app is apparent.

2023-09-24 17:16 UTC, afbjorklund approved these changes

2023-09-24 17:18 UTC, afbjorklund commented
It looks a bit "tiny", compared to the Rancher Desktop logo

2023-09-24 17:24 UTC, balajiv113 commented
Kindly adjust the size here to match the size of other icons 

https://github.com/lima-vm/lima/blob/master/website/data/adoptors.yaml#L16

2023-09-24 17:26 UTC, afbjorklund requested changes
needs the size change, i.e. 200 for this would work?

2023-09-24 18:38 UTC, mairin commented
@afbjorklund any better now?

2023-09-25 01:34 UTC, AkihiroSuda approved these changes
Thanks

2023-09-25 05:17 UTC, afbjorklund commented
> @afbjorklund any better now?

Looking good!

https://deploy-preview-1835--lima-vm.netlify.app/

2023-09-25 05:18 UTC, afbjorklund approved these changes

2023-09-25 07:17 UTC, merged