Change Make default target not to call `clean`
lima-vm/lima pull request #1973
Opened 2023-11-01 08:49 UTC by takanohi

Picking this good first issue.

Ref https://github.com/lima-vm/lima/issues/1053

2023-11-01 12:41 UTC, AkihiroSuda commented on .github/workflows/test.yml
> +      run: make all
`make` has to continue to work

2023-11-01 12:42 UTC, AkihiroSuda requested changes
`make` w/o target has to continue to work

2023-11-01 13:55 UTC, afbjorklund commented
It was also requested to continue to clean...

2023-11-01 22:20 UTC, takanohi commented on .github/workflows/test.yml
> +      run: make all
fixed

2023-11-02 06:45 UTC, afbjorklund commented
I don't think this change is related to the issue that I opened, the question was if make could stop removing `vendor`

This is the code involved with that:

```Makefile
.PHONY: clean
clean:
	rm -rf _output vendor
```

If `make` (or `make all`, same thing) should call clean or not, is more of an optimization issue (over risk of stale build)...

2023-11-02 06:50 UTC, afbjorklund requested changes
I don't think we should add clean only to the "all" target, and remove it from `make`

2023-11-02 08:19 UTC, takanohi commented
@afbjorklund 

You wrote a description in the issue.
`It is fine that it is removed on "clean", but annoying that it is deleted on "make".`

So changing default target will fix your problem immediately. (`make` doesn't remove vendor anymore.)
jandubois also had commented [here](https://github.com/lima-vm/lima/issues/1053#issuecomment-1250126025).

Do you want to remove `clean` process from the whole Makefile?
I think it will be our next action in another PR.

2023-11-02 08:24 UTC, afbjorklund commented
I think they are two different topics, but I am also willing to just do nothing at all (leave as-is)...

If my vendor directory gets wiped, I can do `go mod vendor` again. And avoid to run `make all`
The running of clean and build in parallel is another topic, but there is a workaround in place.
And there are limitations to `go build`, so I think that what we have is "good enough" for now.

2023-11-02 08:26 UTC, afbjorklund commented
@takanohi thanks for offering to help!

2023-11-02 08:39 UTC, takanohi commented
If leaving as-is is ok for you, this PR can be closed.
It's helpful if you close the issue again.

2023-11-02 08:46 UTC, closed without merging