fix limactl shell k3s kubectl command failed
lima-vm/lima pull request #2095
Opened 2023-12-21 09:16 UTC by zhaojizhuang

Fix: #2094

```shell
zjz:~$ limactl shell k3s ls -al /etc/rancher/k3s/k3s.yaml
-rw-r--r-- 1 root root 2961 Dec 21 09:01 /etc/rancher/k3s/k3s.yaml
# has been changed to 644

zjz:~$ limactl shell k3s kubectl get ns
NAME              STATUS   AGE
kube-system       Active   346d
default           Active   346d
kube-public       Active   346d
kube-node-lease   Active   346d
```

2023-12-21 09:23 UTC, zhaojizhuang commented
cc @AkihiroSuda

2023-12-22 07:38 UTC, afbjorklund requested changes
The documentation a the start of the file needs to be changed to match:

```yaml
# Deploy kubernetes via k3s (which installs a bundled containerd).
# $ limactl start ./k3s.yaml
# $ limactl shell k3s sudo kubectl
#
```

2023-12-25 02:25 UTC, zhaojizhuang commented
> The documentation a the start of the file needs to be changed to match:
> 
> ```yaml
> # Deploy kubernetes via k3s (which installs a bundled containerd).
> # $ limactl start ./k3s.yaml
> # $ limactl shell k3s sudo kubectl
> #
> ```

done

2023-12-25 02:25 UTC, AkihiroSuda approved these changes
Thanks

2023-12-25 03:40 UTC, merged