Replacing available commands with basic and advanced commands
lima-vm/lima pull request #2167
Opened 2024-01-27 15:24 UTC by ayushgml

This pull request closes:
 - #2147 

Changes made:
 - Added "github.com/spf13/pflag" package to the project dependencies.
 - Divided the available command list into two - Basic and Advanced commands
 - added the custom help function output using `SetHelpFunc`
 - added a function `printCommands` to print all the commands. Used the function in `SetHelpFunc`.

Output of `limactl help`  after changes:
```
Lima: Linux virtual machines

Usage:
  limactl [command]

Examples:
  Start the default instance:
  $ limactl start

  Open a shell:
  $ lima

  Run a container:
  $ lima nerdctl run -d --name nginx -p 8080:80 nginx:alpine

  Stop the default instance:
  $ limactl stop

  See also template YAMLs: /usr/local/share/lima/templates

Basic Commands:
  create          Create an instance of Lima
  delete          Delete an instance of Lima.
  edit            Edit an instance of Lima
  list            List instances of Lima.
  shell           Execute shell in Lima
  start           Start an instance of Lima
  stop            Stop an instance

Advanced Commands:
  copy            Copy files between host and guest
  disk            Lima disk management
  factory-reset   Factory reset an instance of Lima
  info            Show diagnostic information
  protect         Protect an instance to prohibit accidental removal
  prune           Prune garbage objects
  show-ssh        Show the ssh command line (DEPRECATED; use `ssh -F` instead)
  snapshot        Manage instance snapshots
  sudoers         Generate the content of the /etc/sudoers.d/lima file
  unprotect       Unprotect an instance
  validate        Validate YAML files

Flags:
  --debug           debug mode
  --help            help for limactl
  --log-level       Set the logging level [trace, debug, info, warn, error]
  --tty             Enable TUI interactions such as opening an editor. Defaults to true when stdout is a terminal. Set to false for automation.
  --version         version for limactl

Use "limactl [command] --help" for more information about a command.
```

2024-01-27 15:42 UTC, AkihiroSuda requested changes
Why not use group ID?

See https://github.com/lima-vm/lima/pull/2144/files

2024-01-27 16:18 UTC, ayushgml commented
Sorry @AkihiroSuda! Now I made the necessary changes to implement the fix using groupID.

2024-01-28 23:49 UTC, AkihiroSuda commented on cmd/limactl/main.go
> +
Unneeded change

2024-01-28 23:49 UTC, AkihiroSuda commented on cmd/limactl/copy.go
> +)
Unneeded changes

2024-01-28 23:50 UTC, AkihiroSuda commented
Thanks, but please squash commits

2024-01-29 05:51 UTC, ayushgml commented
> Thanks, but please squash commits

Thank you for reviewing @AkihiroSuda. Now I have squashed the commits.

2024-01-30 12:54 UTC, merged