docs: migrated content for NMNet and user-2 from Network to subfolders
lima-vm/lima pull request #2375
Opened 2024-05-29 06:11 UTC by ayushgml

This issue fixes:
- #1815 

The folder structure now look like this:

![Screenshot 2024-05-29 at 11 40 15 AM](https://github.com/lima-vm/lima/assets/72748253/4f35a052-d142-46ea-bcdb-dc4769267b56)

2024-05-29 07:10 UTC, AkihiroSuda commented
Needs rebase

2024-05-29 07:12 UTC, AkihiroSuda commented on website/content/en/docs/Config/Network/_index.md
>    vm -- "vz" --> vzNAT["vzNAT"]
?

2024-05-29 15:51 UTC, ayushgml commented
@AkihiroSuda I have made the changes and rebase. Can you please update me if any more changes/improvements are required?

2024-06-01 14:55 UTC, AkihiroSuda commented on website/content/en/docs/Config/Network/VMNet/_index.md
> +  vdeVMNet: /opt/vde/bin/vde_vmnet
Seems copied from an old revision

2024-06-01 14:55 UTC, AkihiroSuda requested changes
https://github.com/lima-vm/lima/pull/2375/files#r1623234867

2024-07-08 14:34 UTC, alexandear commented
@ayushgml, could you please update your PR in line with the comments provided above? Thank you!

2024-08-29 07:21 UTC, AkihiroSuda commented
Closing, but feel free to refresh and reopen

2024-08-29 07:21 UTC, closed without merging