Feature/update images
lima-vm/lima pull request #2495
Opened 2024-07-20 12:23 UTC by why168

1. [update .gitignore](https://github.com/lima-vm/lima/commit/65fd28c8b66c018b669448d78127ca99e858f92e)
2. [update ubuntu 24.04 release-20240710](https://github.com/lima-vm/lima/commit/1ce07ab62dabb830fc304e9b32c06591e9bc5171)
3. [update centos-stream-9 20240715](https://github.com/lima-vm/lima/commit/1b30788e11ca346a631fbee28f3523be7586c197)

2024-07-20 22:46 UTC, jandubois commented on .gitignore
> +.DS_Store
These patterns are not specific to the Lima project and therefore don't belong into the repo.

>Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by core.excludesFile in the user’s ~/.gitconfig. Its default value is $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.

(from https://git-scm.com/docs/gitignore)

2024-07-23 04:47 UTC, AkihiroSuda commented on examples/experimental/riscv64.yaml
> +- location: "https://cloud-images.ubuntu.com/releases/24.04/release-20240710/ubuntu-24.04-server-cloudimg-riscv64.img"
digest doesn't seem updated

2024-07-23 04:47 UTC, AkihiroSuda commented on examples/experimental/armv7l.yaml
> +- location: "https://cloud-images.ubuntu.com/releases/24.04/release-20240710/ubuntu-24.04-server-cloudimg-armhf.img"
digest doesn't seem updated

2024-07-23 04:48 UTC, AkihiroSuda commented
Please squash commits

2024-07-24 14:35 UTC, AkihiroSuda commented
Also needs sign-off

2024-07-25 17:36 UTC, AkihiroSuda commented on examples/apptainer-rootful.yaml
> +- location: "https://cloud-images.ubuntu.com/releases/24.04/release-20240710/ubuntu-24.04-server-cloudimg-amd64.img"
Now https://cloud-images.ubuntu.com/releases/24.04/release-20240725/ is available

2024-07-26 10:14 UTC, why168 commented
digest sha256：https://cloud-images.ubuntu.com/releases/24.04/release-20240725/

2024-07-26 15:23 UTC, AkihiroSuda commented on examples/docker.yaml
> +# ⚠️ release-20220309 is known to be broken on aarch64: https://github.com/lima-vm/lima/issues/712
Why mention such ab old version?

2024-07-26 15:24 UTC, AkihiroSuda requested changes
Please sign off the commits and squash them
(1 commit = 1 distro)

2024-07-26 15:26 UTC, AkihiroSuda commented
See https://lima-vm.io/docs/community/contributing/ for how to sign off

2024-07-29 10:21 UTC, why168 commented
> Please sign off the commits and squash them (1 commit = 1 distro)



> 请签署提交并压缩它们 （1 个提交 = 1 个发行版）

finish

2024-07-29 10:58 UTC, AkihiroSuda commented
Still contains an irrelevant merge commit

2024-07-30 03:11 UTC, why168 commented
> Still contains an irrelevant merge commit

fix

2024-07-30 07:22 UTC, AkihiroSuda commented
DCO check is still failing
https://github.com/lima-vm/lima/pull/2495/checks

2024-07-30 08:57 UTC, AkihiroSuda commented
https://github.com/lima-vm/lima/commit/7a23254de278b384d368ecc199087efb0af3bda6.patch

"Edwin.Wu" should be spelled as "Edwin Wu"

2024-07-30 19:00 UTC, AkihiroSuda commented
> archlinux.yaml

Maybe this should be revisited in a separate PR

2024-07-31 10:57 UTC, why168 commented
> > archlinux.yaml
> 
> Maybe this should be revisited in a separate PR

yes， `archlinux.yaml` It's special. build is working fine

2024-07-31 10:57 UTC, why168 commented
> https://github.com/lima-vm/lima/commit/7a23254de278b384d368ecc199087efb0af3bda6.patch
> 
> "Edwin.Wu" should be spelled as "Edwin Wu"

fix

2024-07-31 17:21 UTC, AkihiroSuda commented on examples/almalinux-8.yaml
>  - location: "https://repo.almalinux.org/almalinux/8.9/cloud/aarch64/images/AlmaLinux-8-GenericCloud-8.9-20231128.aarch64.qcow2"
this should be updated too

2024-07-31 17:23 UTC, AkihiroSuda commented
The commit message still inaccurately mention Arch Linux

2024-08-01 02:47 UTC, why168 commented on examples/almalinux-8.yaml
>  - location: "https://repo.almalinux.org/almalinux/8.9/cloud/aarch64/images/AlmaLinux-8-GenericCloud-8.9-20231128.aarch64.qcow2"
finish

2024-08-02 04:23 UTC, AkihiroSuda commented
ping @why168 
https://github.com/lima-vm/lima/pull/2495#issuecomment-2261005469

2024-08-04 08:14 UTC, why168 commented
> 提交消息仍然错误地提到了 Arch Linux

I can't fix it, someone is updating the Arch Linux  https://github.com/lima-vm/lima/pull/2524

2024-08-04 11:26 UTC, AkihiroSuda commented
I don't understand.

2024-08-05 01:13 UTC, merged

2024-08-13 12:18 UTC, AkihiroSuda commented
Images are outdated again.
Do you want to update?

2024-08-14 06:23 UTC, why168 commented
Next version update，🌈 v0.24.0