ci: raise timeout for golangci
lima-vm/lima pull request #3034
Opened 2024-12-19 13:52 UTC by PascalBourdier

to avoid it locally:
```
ERRO Running error: context loading failed: failed to load packages: failed to load packages: failed to load with go/packages: context deadline exceeded
ERRO Timeout exceeded: try increasing it by passing --timeout option
```

2024-12-19 16:43 UTC, jandubois requested changes
I don't see any changes in this comment except for the comment on the existing timeout value. It doesn't match what the PR description says, which also mentions local execution.

2024-12-19 16:43 UTC, jandubois commented on .gitignore
> +.idea/
Please don't put your personal config into the project-specific settings files.

This configuration belongs into your `~/.gitignore` file, so it applies to all your repos.

2024-12-19 16:43 UTC, jandubois commented on .golangci.yml
> +  timeout: 2m # 1m by default
Our YAML linter rules requires at least 2 spaces before a comment:

```suggestion
  timeout: 2m  # 1m by default
```

2024-12-19 17:54 UTC, PascalBourdier commented
> I don't see any changes in this comment except for the comment on the existing timeout value. It doesn't match what the PR description says, which also mentions local execution.

I fixed it according you review

2024-12-22 23:23 UTC, AkihiroSuda approved these changes
Thanks

2024-12-22 23:24 UTC, merged

2024-12-22 23:24 UTC, AkihiroSuda commented
Next time please squash the commits