Fix SSH command escaping
lima-vm/lima pull request #633
Opened 2022-02-06 15:18 UTC by buu700

Addresses https://github.com/lima-vm/lima/issues/632.

I haven't tested very thoroughly, and may be making some incorrect assumptions about how shellescape works, but I can confirm that this at least fixes the `lima bash -c "$(echo -e '\n\techo balls\n')"` example for me.

2022-02-06 18:42 UTC, jandubois requested changes
This is not sufficient, as it doesn't deal with commands that include quotes. E.g. it breaks:

```console
$ lima bash -c 'echo "foo bar"'
foo bar
```

With the current patch is breaks like this:

```console
$ lima bash -c 'echo "foo bar"'
bar': -c: line 1: unexpected EOF while looking for matching `''
bar': -c: line 2: syntax error: unexpected end of file
```

2022-02-06 19:07 UTC, buu700 commented
All right, should be good now. Thanks @jandubois!

As an aside, both of these examples would be good test to add for the future.

2022-02-06 19:41 UTC, jandubois approved these changes
LGTM, but since you volunteered to add tests (😄 ), maybe add them to this PR?

2022-02-06 20:15 UTC, buu700 commented
lol, all right, done. I confirmed that the new tests currently pass, and each one also fails as expected with the two previous versions of shell.go.

2022-02-07 02:22 UTC, AkihiroSuda commented
Thanks, but please sign the commit for DCO
https://github.com/apps/dco

(run `git commit -a -s --amend`, and make sure that the `Signed-off-by: NAME <EMAIL>` line with your real name is included in the commit message)

2022-02-07 02:23 UTC, buu700 commented
Done.

2022-02-07 05:14 UTC, jandubois approved these changes
Thanks!

2022-02-07 05:14 UTC, merged